version: '3.8'

services:
  mlflow:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001

  train:
    build: .
    command: python train.py
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001
    depends_on:
      - mlflow 